openapi: 3.0.3
info:
  title: Todo Service
  description: |-
    This is a sample todo service 
  version: 1.0.0
paths:
  /hello:
    get:
      description: return greeting message
      operationId: hello
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: string

  /tasks:
    get:
      description: Returns a list of tasks
      parameters:
        - name: limit
          in: query
          description: Limits the number of items on a page
          schema:
            type: integer
        - name: offset
          in: query
          description: Specifies the page number of the tasks to be displayed
          schema:
            type: integer
      responses:
        '200':
          description: Successfully returned a list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      description: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: Successfully created a new task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'

components:
  schemas:
    Task:
      type: object
      required:
        - task_name
      properties:
        task_name:
          type: string
        description:
          type: string
