services:
  todo-app:
    platform: "linux/x86_64"
    build: .
    ports:
      - "8944:8944"
    depends_on:
      cassandra-setup:
        condition: service_completed_successfully
    command: --spring.cassandra.contact-points=cassandra
  cassandra:
    platform: "linux/arm64/v8"
    image: "cassandra:4.1.2"
    healthcheck:
      test: [ "CMD", "cqlsh" ]
      interval: 30s
      timeout: 10s
      retries: 5
  cassandra-setup:
    platform: "linux/arm64/v8"
    image: "cassandra:4.1.2"
    depends_on:
      cassandra:
        condition: service_healthy
    entrypoint: [ "cqlsh", "cassandra", "-e", "create keyspace if not exists todo with replication = {'class' : 'SimpleStrategy', 'replication_factor' : 1};"]
